version: '3'
services:
  db-pg:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres